export const SCREEN_ROUTES = {
  TenantLogin1: '/screens/tenant-login-1',
  Support: '/screens/support',
  TenantLogin4: '/screens/tenant-login-4',
  OtpSignup: '/screens/otp-signup',
  TermsAndConditions: '/screens/terms-and-conditions',
  TenantLogin2: '/screens/tenant-login-2',
  MblNumberSignup: '/screens/mbl-number-signup',
  TenantLogin3: '/screens/tenant-login-3',
  RequestSent: '/screens/request-sent',
  Register: '/screens/register',
  RequestSent2: '/screens/request-sent-2',
  RequestSent3: '/screens/request-sent-3',
  HstlCode: '/screens/hstl-code',
  RequestApproval: '/screens/request-approval',
  HstlDetailsTenant: '/screens/hstl-details-tenant',
  RequestApproval2: '/screens/request-approval-2',
  DraftsNotices: '/screens/drafts-notices',
  Complaints: '/screens/complaints',
  AnimationReqSent: '/screens/animation-req-sent',
  AnimationReqSent2: '/screens/animation-req-sent-2',
  AnimationReqSent3: '/screens/animation-req-sent-3',
  TermsConditions: '/screens/terms-conditions',
  AnimationReqSent4: '/screens/animation-req-sent-4',
  Terms: '/screens/terms',
} as const;
